#!/usr/bin/env bash
./generate_training_data_of_lidar_data "$1" "$2/sp4" 0.4
./generate_training_data_of_lidar_data "$1" "$2/sp5" 0.5
./generate_training_data_of_lidar_data "$1" "$2/sp6" 0.6
./generate_training_data_of_lidar_data "$1" "$2/sp7" 0.7
./generate_training_data_of_lidar_data "$1" "$2/sp8" 0.8
./generate_training_data_of_lidar_data "$1" "$2/sp9" 0.9
./generate_training_data_of_lidar_data "$1" "$2/1sp" 1.0
